### ISSUE TITLE
cli: implement all the write commands

### ISSUE THREAD

**Issue by audrium** [reanahub/reana-client-go#122]
This is an epic umbrella issue to hold a list of all the write commands which needs to be implemented in the go client:

- [ ] `create` 
- [x] `delete` https://github.com/reanahub/reana-client-go/issues/93
- [x] `restart` https://github.com/reanahub/reana-client-go/pull/125
- [ ] `run`
- [x] `start` https://github.com/reanahub/reana-client-go/issues/95
- [x] `stop` https://github.com/reanahub/reana-client-go/pull/127
- [x] `mv`https://github.com/reanahub/reana-client-go/issues/97
- [x] `rm` https://github.com/reanahub/reana-client-go/issues/96
- [ ] `download`
- [ ] `upload`
- [x] secrets-* commands: add, delete, list

**Comment by audrium** [comment]
Closing since most of the commands are already implemented and the remaining ones have a dedicated issues
