### ISSUE TITLE
cli: implement all the read only commands

### ISSUE THREAD

**Issue by audrium** [reanahub/reana-client-go#23]
This is an epic umbrella issue to hold a list of all the read only commands which needs to be implemented in the go client:
- [x] `quota-show`: https://github.com/reanahub/reana-client-go/issues/28
- [x]  `info`
- [x] `ping`
- [x] `version`
- [x] `diff`: https://github.com/reanahub/reana-client-go/issues/32
- [x] `list`: https://github.com/reanahub/reana-client-go/issues/27
- [x] `logs`: https://github.com/reanahub/reana-client-go/issues/31
- [x] `status`: https://github.com/reanahub/reana-client-go/issues/30
- [ ] `validate`
- [ ] `download`
- [x] `du`: https://github.com/reanahub/reana-client-go/issues/18
- [x] `ls`: https://github.com/reanahub/reana-client-go/issues/20
- [x] interactive commands: `open`, `close` https://github.com/reanahub/reana-client-go/issues/29

**Comment by audrium** [comment]
Closing since most of the commands are already implemented and the remaining ones have a dedicated issues
