### ISSUE TITLE
cli: implement all `list` command flags

### ISSUE THREAD

**Issue by audrium** [reanahub/reana-client-go#27]
Right now we have a basic version of `list` command with some flags already working. We need to implement all the other flags and replicate all the functionality we have in `reana-client`.

Here is a list of all the flags `list` command have:
- [x] `-w, --workflow TEXT List all runs of the given workflow.`
- [x] `-s, --sessions List all open interactive sessions.`
- [ ] `--format TEXT Format output according to column titles or column values. `
- [x]  `--json Get output in JSON format.`
- [x] `--all Show all workflows including deleted ones.`
- [x] `-v, --verbose Print out extra information: workflow id, user id, disk usage, progress, duration.`
- [x] `-h, --human-readable Show disk size in human readable format.`
- [ ] `--sort TEXT Sort the output by specified column`
- [x] `--filter TEXT Filter workflow that contains certain filtering criteria.`
- [x] `--include-duration Include the duration of the workflows in seconds.`
- [x] `--include-progress Include progress information of the workflows.`
- [x] `--include-workspace-size Include size information of the workspace.`
- [x] `--show-deleted-runs Include deleted workflows in the output.`
- [x] pagination (`--page`, `--size`)

This is an epic issue which can be used to link all the PRs used to develop these features
